### PR TITLE
Fix incorrect aggregations in CMP ES results

### LINKED ISSUE #99: Filter numbers are incorrect when using CMP
**Magento 2 version(s) used**: x.y.z
**Extension version(s) affected**: x.y.z

**Description**  
Number of product in filters is incorrect due to calculating aggregations on the subset of the category while using CMP.
Solution would be to use `post_filter` on the elasticsearch query, so the aggregations will be correct. 

**How to reproduce**  

**Magento 2 mode**
- [ ] Developer 
- [ ] Production

**Full page cache**
- [ ] Enabled 
- [ ] Disabled

**Possible Solution**  

**Additional context**

### PR DESCRIPTION
**Pull request by olsi-qose**
## Description
The number of products displayed on the filters of the layered navigation are incorrect when using the `Sort Relevance`. 

The module alters the request attributes in Magento, which later alters the Elasticsearch query. To make CM work, the module removes previous query terms and applies only the term to query a specific list of ids. Only the documents containing these ids are returned. As a result the aggregation are applied only of a subset of the category.

ES offers the possibility to do [post filtering](https://www.elastic.co/guide/en/elasticsearch/reference/7.x/filter-search-results.html#post-filter) query. Magento's elasticsearch module does not offer the flexibility to add `post_filters` to the ES query, so our module intercepts `Magento\Elasticsearch\Elasticsearch5\SearchAdapter\Mapper::buildQuery` function and adds the needed attributes to the new map being passed to the ES client. 

image

## Related Issue
Fixes #99 

## How Has This Been Tested?
Manually

## Checklist:
- [ ] My code follows the code style of this project.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] I have assigned the correct milestone or created one if non-existent.
- [ ] I have correctly labeled this pull request.
- [ ] I have linked the corresponding issue in this description.
- [ ] I have updated the corresponding Jira ticket.
- [ ] I have requested a review from at least 2 reviewers
- [ ] I have checked the base branch of this pull request
- [ ] I have checked my code for any possible security vulnerabilities

### CODE REVIEW

File: Plugin/Elasticsearch/SearchAdapter/Mapper.php [hunk 1]
```diff
@@ -0,0 +1,59 @@
...
+{
+    const POST_FILTER = 'post_filter';
+
+    public function afterBuildQuery(MagentoMapper $mapper, array $searchQuery, RequestInterface  $request)
+    {
+        if ($request instanceof NostoSearchRequest) {
+            $postFilter = $request->getPostFilter();
+            if ($postFilter !== null) {
+
+                $searchQuery['body']['post_filter']['bool']['must'][0]['terms']['_id'] = $postFilter->getReference()->getMust()['prod_ids']->getValue();
```
Comment (mridang) [inline Plugin/Elasticsearch/SearchAdapter/Mapper.php:54]: Ideally, you would use the filter-builder from Magento. We can then make this pull request upstream to the Magento core too.

File: Plugin/Framework/Search/Request/Builder.php [hunk 2]
```diff
@@ -0,0 +1,83 @@
...
+     * @return RequestInterface
+     * @noinspection RedundantSuppression
+     */
+    // phpcs:ignore Generic.CodeAnalysis.UnusedFunctionParameter
+    public function afterCreate(MagentoRequestBuilder $builder, RequestInterface $request)
+    {
+        $query = $request->getQuery();
+        if ($query instanceof BoolExpression && RequestUtils::containsBoolNostoSearchQuery($query)) {
+            /** @var NostoSearchRequest $nostoRequest */
+            $nostoRequest =  $this->objectManager->create(
```
Comment (mridang) [inline Plugin/Framework/Search/Request/Builder.php:75]: Why can't you simply wrap **all** queries - why does it need to be a bool query or a Nosto query? Would it really maatter?

**Review by mridang — APPROVED** [review]
