### PR TITLE
Hotfix/1.2.1 - Fix array to string conversion in Sortby plugin

### LINKED ISSUE #55: Array to string conversion bug in the Sortby plugin
**Magento 2 version(s) used**: x.y.z
**Extension version(s) affected**: x.y.z

**Description**  
Fix array to string conversion for the Nosto sorting option in the admin catalog page

**How to reproduce**  

**Magento 2 mode**
- [ ] Developer 
- [ ] Production

**Full page cache**
- [ ] Enabled 
- [ ] Disabled

**Possible Solution**  

**Additional context**

### PR DESCRIPTION
**Pull request by olsi-qose**
## Description
Fix array to string conversion for the Nosto sorting option in the admin catalog page

## Related Issue
closes #55 

## Checklist:
- [ ] My code follows the code style of this project.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] I have assigned the correct milestone or created one if non-existent.
- [ ] I have correctly labeled this pull request.
- [ ] I have linked the corresponding issue in this description.
- [ ] I have updated the corresponding Jira ticket.
- [ ] I have requested a review from at least 2 reviewers
- [ ] I have checked the base branch of this pull request
- [ ] I have checked my code for any possible security vulnerabilities

### CODE REVIEW

File: Plugin/Catalog/Model/Sortby.php [hunk 1]
```diff
@@ -102,7 +102,7 @@ public function afterGetAllOptions( // phpcs:ignore Generic.CodeAnalysis.UnusedF
         ) {
             // new option
             $customOption = [
-              ['label' => __(['Relevance']), 'value' => NostoHelperSorting::NOSTO_PERSONALIZED_KEY]
```
Comment (mridang) [inline Plugin/Catalog/Model/Sortby.php:105]: Why is this not caught by Phan?

Comment (olsi-qose) [reply Plugin/Catalog/Model/Sortby.php:105]: Not sure why, need to look further into that
