### PR TITLE
Replace FulltextCollection with ProductCollection

### LINKED ISSUE #29: Product\Collection is used from other modules.
**Magento 2 version(s) used**: x.y.z
**Extension version(s) affected**: x.y.z

**Description**  
CMP module crashes as it expects `Fulltext\Collection` to be used in the Toolbar.php class. 
**How to reproduce**  

**Magento 2 mode**
- [ ] Developer 
- [ ] Production

**Full page cache**
- [ ] Enabled 
- [ ] Disabled

**Possible Solution**  

**Additional context**

### PR DESCRIPTION
**Pull request by olsi-qose**
## Description
After trying to integrate with another module, noticed that `Product\Collection` is used instead of `Fulltext\Collection`. This way the module was crashing. 

## Related Issue
closes #29

## Checklist:
- [x] My code follows the code style of this project.
- [x] I have assigned the correct milestone or created one if non-existent.
- [x] I have correctly labeled this pull request.
- [x] I have linked the corresponding issue in this description.
- [x] I have updated the corresponding Jira ticket.
- [x] I have requested a review from at least 2 reviewers
- [x] I have checked the base branch of this pull request
- [x] I have checked my code for any possible security vulnerabilities

### CODE REVIEW

File: Plugin/Catalog/Block/Toolbar.php [hunk 1]
```diff
@@ -171,12 +171,12 @@ public function afterSetCollection(
...
     /**
      * @param Store $store
-     * @param FulltextCollection $collection
+     * @param ProductCollection $collection
      * @return CategoryMerchandisingResult|null
      * @throws NostoException
      * @throws LocalizedException
      */
-    private function getCmpResult(Store $store, FulltextCollection $collection)
+    private function getCmpResult(Store $store, ProductCollection $collection)
```
Comment (hannunosto) [inline Plugin/Catalog/Block/Toolbar.php]: ProductCollection is not used, let's remove it

File: Plugin/Catalog/Block/Toolbar.php [hunk 2]
```diff
@@ -141,12 +141,12 @@ public function afterSetCollection(
...
             try {
-                /* @var FulltextCollection $subjectCollection */
+                /* @var ProductCollection $subjectCollection */
                 $subjectCollection = $subject->getCollection();
                 $this->setLimit($subjectCollection->getPageSize());
                 $result = $this->getCmpResult($store, $subjectCollection);
                 if ($result instanceof CategoryMerchandisingResult
-                    && $subjectCollection instanceof FulltextCollection
+                    && $subjectCollection instanceof ProductCollection
                 ) {
```
Comment (hannunosto) [inline Plugin/Catalog/Block/Toolbar.php]: Short circuit and throw exception here the instances are not what we need
